#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 2
# @author    Gerik Bonaert <dev@adaxisoft.be>
# @copyright Copyright (c) 2013 Gerik Bonaert
#
# Freelan for OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

case "$1" in
	configure)
		########################################################################
		# Create essencial user.
		# All services that do not require any specific user should use the 
		# essential user. This was done to avoid using root.
		########################################################################

		if ! getent passwd essencia >/dev/null 2>&1; then
		  useradd --system --groups users --no-user-group --create-home --home-dir /var/lib/essencia --shell /usr/sbin/nologin essencia
		fi
		
		########################################################################
		# Add repositories
		#  - Btsync
		#  - Freelan
		#  - adaxisoft.be
		#  - debian contrib and non-free
		########################################################################
		
		echo "deb http://ftp.belnet.be/debian/ wheezy contrib non-free" > /etc/apt/sources.list.d/contrib.list
		apt-key adv --keyserver keys.gnupg.net --recv-keys 6BF18B15
		echo "deb http://debian.yeasoft.net/btsync wheezy main" > /etc/apt/sources.list.d/btsync.list
		
		echo "deb http://debian.freelan.org/ wheezy-backports main" > /etc/apt/sources.list.d/freelan.list
		wget -q http://debian.freelan.org/debian.freelan.org.key -O- | apt-key add -
		
		echo "deb http://apt.adaxisoft.be/debian wheezy main" > /etc/apt/sources.list.d/essencia.list
		wget -q http://apt.adaxisoft.be/public.gpg.key -O- | apt-key add -
		
		echo "deb http://packages.openmediavault.org/public/ kralizec main" > /etc/apt/sources.list.d/openmediavault.list
		echo "deb http://packages.omv-extras.org/debian/ kralizec main" >> /etc/apt/sources.list.d/openmediavault.list
		echo "deb http://packages.omv-extras.org/debian/ kralizec-testing main" >> /etc/apt/sources.list.d/openmediavault.list
		echo "deb http://packages.omv-extras.org/debian/ kralizec-btsync main" >> /etc/apt/sources.list.d/openmediavault.list		
        
		wget -q http://packages.openmediavault.org/public/archive.key -O- | apt-key add -
		
		cat <<EOF | apt-key add -
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.12 (GNU/Linux)

mQENBFFUkpABCADUDMDaXzjzq20QJTAz1eqnjq7n1p+DT8caZ6CkFWhK30TEB+qf
C5OBWGoBcZXRtftvDski2tZKU3MtlRJzZtAllAw5CQ2xQlMkRZmPQuVbRiRKl7vZ
Rt0wwWf36RVUOKkBgN6h1F8wHUQ21vuth60M/LwQDceFT5EZfySAOkum+W+hDEpa
LaRsYAhVQZIIWSNbXtIORPTybTEr27JiVM5Q1Bc5EAQ8zuIA1uSIlDY9wgqa9iRW
iq/cx+wrIXGiQYylLXoO1ZQrN4ZyvPQ5Ajwoxexv96ow01qKQFWClVoiGh3eVka5
cgv6RYp3H117XcYddXTYG1ZsdZSRwmSb/zWnABEBAAG0I0Fhcm9uIE11cnJheSA8
YWFyb24yN0ByeWVjb2luYy5jb20+iQE4BBMBAgAiBQJRVJKQAhsDBgsJCAcDAgYV
CAIJCgsEFgIDAQIeAQIXgAAKCRCqowNrMLIwimQNB/9RO00PqLRWGaYOyauz8e6t
cddDclnn12GU3IQX1QimchhQtOwfVsVoUVE1LcAoR09mIGfXNVHAWqIwENVqcZjD
nZCGFznOC4AOEaBk05Hgbf5lcFvbWMLYA3KLSvUW/WA/DwJ6Togqr7pwfqZoWaVO
VJIgVC0tz7jGskWLk7lnNCc3EKShTro3Jyq4j9y+3pa5IV1LAvuEhPlj/3dSgkVA
3Ey1qv5kppFOQXKtaV9c9AjjsrmzmKQtTnpLMUSXIck9mqsi1FhxwsyKFvX44c8/
g9IRQlZRJBeqpwkDfn/OK8mZZ9z5aM6cCjATu16gCvjEoRqTyxconQQ1cneEYoWd
uQENBFFUkpABCACv84lwfpa0WTqrAFFOP/NAvDxT+F5E7Bfkm3uHjFtqdBG/70CC
JGuj3RznIUJusAIEkWvBdx/lOkrBEEYLpVf60dwVI79mxkJBRd+R2g5ZlNfXaxKb
FnMlPq37vZ9qFIBvWYbbSpJJYn0NbMS1JrePYRucfseBfiLUnECrLCs+c9eb5v1V
JphBKxj+cHcTXkmyhgKnQRRvUG3CfkRSElTumbWUWbG5kO82cMG/QooYp0+T8ljk
kkdFKVCZsAoFh6VmX63N6sTIfaV8bsnG8kFzAD2G+JmbCLhf8Vu8iLupzhL1vbpX
P72/yVP9UuLMQHPxy9s7KN6SC105ISV69G7HABEBAAGJAR8EGAECAAkFAlFUkpAC
GwwACgkQqqMDazCyMIrKAQf+LgiB63GP7pH2zimzZ6CdOPi9D/z8vSVQo1UECfVs
ZOtPupnzVTr58W4TdoPDO4tBY3Aap1MsFEeBbH1ozF+s4d7sXIRMDL1y/SlDclJd
1u6iikLDsbKaLd+mkRDte2jqhSkVUftxiJwQejs2f5YwmXdVsTD0XVtj7PEH5pXg
HMzqEeK6DYAJ34J1oSvbdYWQa3mTFs2i2cuJMc7JzjzW50Ip5s8+IUJXkSD0+yem
nY5SIhWG2kS1HW5QTmAgmMqMsvGKJS23gwjUv3l/UWJBS7MNx93LoWWbSt/uZCxK
T/Zc8RDKTDUUbs6riM5zMBbbbukttrGkbE/dnyNKU7wrnA==
=hMRE
-----END PGP PUBLIC KEY BLOCK-----
EOF
		
		
	;;

	abort-upgrade|abort-remove|abort-deconfigure)
	;;

	*)
		echo "postinst called with unknown argument '$1'" >&2
		exit 1
	;;
esac

exit 0
